INFO:root:DEBUG mode is on
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): raw.githubusercontent.com:443
DEBUG:urllib3.connectionpool:https://raw.githubusercontent.com:443 "GET /JeffAxe123/miniProjects/v2/languages/launcher/en.lang HTTP/1.1" 404 14
ERROR:root:Extra data: line 1 column 4 (char 3)
Traceback (most recent call last):
  File "C:\Users\18lew\jar_launchers\Java miniProjects\launcher.pyw", line 125, in <module>
    with open(config["languages-folder"] + "/launcher/" + options["lang"] + ".lang") as lang:
FileNotFoundError: [Errno 2] No such file or directory: 'languages/launcher/en.lang'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\18lew\jar_launchers\Java miniProjects\launcher.pyw", line 137, in <module>
    lang = json.load(lang)
  File "C:\Users\18lew\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\18lew\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\18lew\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)
INFO:root:Process exited with code 1
